version: '3.2'

services:
  adx-api: 
    image: ghcr.io/airdex-monitoring/adx-api:latest
    ports:
      - '8080:8080'
    environment:
      ADX_DATASOURCE_URL: 
      ADX_DATASOURCE_USERNAME: 
      ADX_DATASOURCE_PASSWORD: 
    networks:
      - adx-shared-network
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

networks:
  adx-shared-network:
    external: true
